name: EBAC CI

on:
    push:
        branches: [ ci-cbs ]

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4.1.0
          - uses: actions/setup-node@v3.8.1
            with:
                node-version: '18.18.2'
          - name: Cypress run
            uses: cypress-io/github-action@v6.3.0
            continue-on-error: true
            with:
                install-command: npm install
                browser: chrome
                start: npm run cy:run-ci
          - name: Publish Report
            uses: peaceiris/actions-github-pages@v3.1.12
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./mochawesome-report
